name: Build and Deploy DotNet project to Azure Function App

env:
  AZURE_FUNCTIONAPP_NAME: ImageProcessor           # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './ImageProcessor'              # set this to the path to your web app project, defaults to the repository root
  # DOTNET_VERSION: '3.1.301'                        # set this to the dotnet version to use

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal